dev_portal/dev_portal/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'links.views.index', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^links/', include('links.urls', namespace='links')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^wanikani/', include('wanikani.urls', namespace='wanikani')),
)

dev_portal/links/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from links import views

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
  url(r'^details/(?P<pk>\d+)', login_required(views.LinkView.as_view()), name='details'),
  url(r'^list/', views.list, name='list'),
  url(r'^main\.js', views.mainjs, name='mainjs'),
)

dev_portal/links/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Link(models.Model):
  title = models.CharField(max_length=250)
  added = models.DateTimeField('date added')
  url = models.CharField(max_length=512)
  user = models.ForeignKey(User)

  def __str__(self):
    return self.url

dev_portal/links/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from links.models import Link
from django.views import generic
from django.core import serializers
from django.http import HttpResponse

class LinkView(generic.DetailView):
  model=Link
  template_name = 'links/details.html'

# Create your views here.
#@login_required
def index(request):
  if request.user.is_authenticated():
    l = Link.objects.filter(user=request.user)
  else:
    l = []
  #l = Link.objects.all()
  context  = {'list': l}
  return render(request, 'links/index.html', context)

@login_required
def list(request):
  return HttpResponse(
            serializers.serialize('json',
              Link.objects.filter(user=request.user)),
            content_type='application/json')

def mainjs(request):
  return render(request, 'links/js/main.js', content_type='application/javascript')

dev_portal/links/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Portal title stuff{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'links/css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'links/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'links/css/main.css' %}">

        <script src="{% static 'links/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-collapse collapse">
          {% if user.is_authenticated %}
            <a href="{% url 'wanikani:details' %}">Hello, {{user.username}}</a>
          {% else %}
            <a href="{% url 'login' %}">Login</a>
          {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </div>
<div class="container">
  <div class="row">

      <script type="text/x-handlebars">

        <div class="col-sm-2">
        {% verbatim %}{{ view App.LinkListView }}{% endverbatim %}
        </div>
        <div class="col-sm-10">
          {% verbatim %}{{outlet}}{% endverbatim %}
        </div>

      </script>



</div>

    </div> <!-- /container -->
    {% verbatim %}
    <script type="text/x-handlebars" data-template-name="index">
    </script>
    <script type="text/x-handlebars" data-template-name="linklist">
      <ul class='list list-unstyled'>
      {{#each App.LinkList}}
        <li><a {{ bind-attr href=url }}>{{ title }}</a></li>
      {{/each}}
      <li>{{#link-to 'gradesentence'}}Grade Sentence{{/link-to}}</li>
      <li>{{#link-to 'listsentences'}}Saved Sentences{{/link-to}}</li>
      </ul>
    </script>
    <script type="text/x-handlebars" data-template-name="gradesentence">
      <form role="form">
      <div class="form-group">
        <div>
          {{textarea value=jptext cols="75" rows="10" class="form-control" placeholder="Ungraded text"}}
        </div>
        <button {{action 'grade' }} class="btn btn-primary">Grade</button>
        <button {{action 'savesentence' }} class="btn">Save Sentence</button>
        </div>
        <div class="form-group">
        <div>{{input type="text" class="form-control" value=apikey placeholder="API Key"}}</div>
        <button {{action 'savekey'}} class="btn">Set Key</button>
        </div>
      </form>
      <p>{{#each graded_text }}<span {{ bind-attr class=status}}>{{ character }}</span>{{/each}}</p>
    </script>
    <script type="text/x-handlebars" data-template-name="listsentences">
      <ul class='list'>
      {{#each model}}
        <li>{{ fields.sentence }}</li>
      {{/each}}
      </ul>
    </script>
    {% endverbatim %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static 'links/js/vendor/jquery-1.11.0.min.js' %}"><\/script>')</script>

        <script src="{% static 'links/js/vendor/handlebars-1.1.2.js' %}"></script>
        <script src="{% static 'links/js/vendor/ember-1.6.1.js' %}"></script>
        <script src="{% static 'links/js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% url 'links:mainjs' %}"></script>
    </body>
</html>